local colours = {
	black = Color3.new(0, 0, 0),
	blue = Color3.new(0.05, 0.64, 0.87),
	dark_blue = Color3.new(0.03, 0.59, 0.81),
	dark_desaturated_red = Color3.new(0.52, 0.24, 0.25),
	dark_grey = Color3.new(0.27, 0.27, 0.27),
	desaturated_red = Color3.new(0.69, 0.30, 0.31),
	green = Color3.new(0.52, 0.87, 0.20),
	light_grey = Color3.new(0.79, 0.79, 0.79),
	grey = Color3.new(0.5, 0.5, 0.5),
	orange = Color3.new(0.90, 0.49, 0.13),
	purple = Color3.new(0.61, 0.35, 0.71),
	red = Color3.new(1, 0.39, 0.39),
	white = Color3.new(1, 1, 1),
}

colours.error = colours.red
colours.info = colours.blue
colours.success = colours.green

return colours
