local keybinds = {
	components_showcase = Enum.KeyCode.C,
	debug_local = Enum.KeyCode.P,
	debug_server = Enum.KeyCode.M,
	slot = {
		[1] = Enum.KeyCode.One,
		[2] = Enum.KeyCode.Two,
		[3] = Enum.KeyCode.Three,
		[4] = Enum.KeyCode.Four,
		[5] = Enum.KeyCode.Five,
		[6] = Enum.KeyCode.Six,
		[7] = Enum.KeyCode.Seven,
		[8] = Enum.KeyCode.Eight,
		[9] = Enum.KeyCode.Nine,
	},
	tablist = Enum.KeyCode.Tab,
	tool_switch = Enum.KeyCode.E,
	tool_use = Enum.UserInputType.MouseButton1,
}

return keybinds
